[CHATS-420] Fixed script for DB migration

diff --git a/package/carbonio-chats-messaging b/package/carbonio-chats-messaging
--- a/package/carbonio-chats-messaging
+++ b/package/carbonio-chats-messaging
@@ -18,16 +18,6 @@ if [[ "$1" != "setup" ]]; then
 fi
 
 MAIN_SERVICE_NAME="carbonio-chats-messaging"
-get_consul_kv() {
-  KEY=$1
-  CONSUL_VALUE=$(consul kv get "$MAIN_SERVICE_NAME/$KEY")
-}
-get_consul_kv "db-password" >/dev/null 2>&1; DB_PASSWORD=$CONSUL_VALUE
-if [[ "$DB_PASSWORD" == "" ]]; then
-  echo "Carbonio Chats Messaging database password not found."
-  echo "Please install carbonio-chats-messaging-db and run carbonio-chats-messaging-db-bootstrap command."
-  exit 1
-fi
 
 config_variant() {
   VARIANT=$1
@@ -87,14 +77,28 @@ EOF
     systemctl daemon-reload
 fi
 
-sed "s/<insert-password>/$DB_PASSWORD/" etc/carbonio/chats-messaging/mongooseim.toml -i
+get_consul_kv() {
+  KEY=$1
+  CONSUL_VALUE=$(consul kv get "$MAIN_SERVICE_NAME/$KEY")
+}
+get_consul_kv "db-password" >/dev/null 2>&1; DB_PASSWORD=$CONSUL_VALUE
+if [[ "$DB_PASSWORD" == "" ]]; then
+  echo "Carbonio Chats Messaging database password not found."
+  echo "Please install carbonio-chats-messaging-db and run carbonio-chats-messaging-db-bootstrap command."
+  exit 1
+fi
+sed "s/<insert-password>/$DB_PASSWORD/" /etc/carbonio/chats-messaging/mongooseim.toml -i
 
 consul reload
 
 # Limit token visibility as much as possible
 export -n CONSUL_HTTP_TOKEN
 
-carbonio-chats-messaging-migration
+echo "======================================================================================="
+echo "Carbonio chats messaging correctly set!"
+echo "You must run carbonio-chats-messaging-migration to check database consistency."
+echo "Syntax: [PGPASSWORD=password] carbonio-chats-messaging-migration username [host] [port]"
+echo "======================================================================================="
 
 systemctl restart carbonio-chats-messaging-auth.service
 systemctl restart carbonio-chats-messaging.service
diff --git a/package/carbonio-chats-messaging-migration b/package/carbonio-chats-messaging-migration
--- a/package/carbonio-chats-messaging-migration
+++ b/package/carbonio-chats-messaging-migration
@@ -1,37 +1,64 @@
 #!/bin/bash
 
+function syntax() {
+    echo "Syntax: [PGPASSWORD=password] $0 username [host] [port]"
+    exit 1
+}
+set -e
+
 if [[ $(id -u) -ne 0 ]]; then
   echo "Please run as root"
   exit 1
 fi
 
-initial_schema="/etc/carbonio/chats-messaging/sql-scripts/initial-schema.sql"
-migrations_folder="/etc/carbonio/chats-messaging/sql-scripts/migrations/"
-postgres_folder="/var/lib/postgresql"
-is_working=false
-db_name="carbonio-chats-messaging-db"
-db_username="postgres"
+if [[ -z "$1" ]]; then
+  syntax;
+fi
 
-initial_folder=$(pwd)
+INITIAL_SCHEMA_FILE="/etc/carbonio/chats-messaging/sql-scripts/initial-schema.sql"
+MIGRATIONS_FOLDER="/etc/carbonio/chats-messaging/sql-scripts/migrations/"
+IS_WORKING=false
+DATABASE_NAME="carbonio-chats-messaging-db"
+DATABASE_USERNAME="carbonio-chats-messaging-db"
+
+INITIAL_FOLDER=$(pwd)
+
+NOT_ASK_FOR_PGPASSWORD='-w'
+if [[ -z "${PGPASSWORD}" ]]; then
+  NOT_ASK_FOR_PGPASSWORD=''
+fi
+
+ROOT_DB_USERNAME="$1"
+POSTGRES_HOST=$2
+POSTGRES_PORT=$3
+
+if [ -z "${POSTGRES_HOST}" ]; then
+  POSTGRES_HOST="127.0.0.1";
+fi
+
+if [ -z "${POSTGRES_PORT}" ]; then
+  POSTGRES_PORT="5432";
+fi
+
 run_script_file() {
-  sudo -u postgres bash -c "psql -U $db_username -d $db_name -f $1 -qtAX"
+  psql -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -U "${ROOT_DB_USERNAME}" "${NOT_ASK_FOR_PGPASSWORD}" "${DATABASE_NAME}" -f "$1" -qtAX
   return $?
 }
 
 get_pgsql_value() {
-  pgsql_value=$(sudo -u postgres bash -c "psql -U $db_username -d $db_name -c '$1' -qtAX")
-  if [[ $1 -ne 0 ]]; then
-    pgsql_value=""
+  PGSQL_VALUE=$(psql -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -U "${ROOT_DB_USERNAME}" "${NOT_ASK_FOR_PGPASSWORD}" "${DATABASE_NAME}"  -c "$1" -qtAX)
+  if [[ $? -ne 0 ]]; then
+    PGSQL_VALUE=""
   fi
   return $?
 }
 
 format_version() {
-  IFS='.' read -r -a version_tokens <<< "$1"; unset IFS
-  printf -v major "%05d" "${version_tokens[0]}"
-  printf -v minor "%05d" "${version_tokens[1]}"
-  printf -v patch "%05d" "${version_tokens[2]}"
-  formatted_version="$major.$minor.$patch"
+  IFS='.' read -r -a VERSION_TOKENS <<< "$1"; unset IFS
+  printf -v MAJOR "%05d" "${VERSION_TOKENS[0]}"
+  printf -v MINOR "%05d" "${VERSION_TOKENS[1]}"
+  printf -v PATCH "%05d" "${VERSION_TOKENS[2]}"
+  FORMATTED_VERSION="$MAJOR.$MINOR.$PATCH"
 }
 
 exit_with_error_management() {
@@ -42,60 +69,81 @@ exit_with_error_management() {
     if [[ $message != "" ]]; then
       echo "$message"
     fi
-    cd "$initial_folder" || exit 1
+    cd "$INITIAL_FOLDER" || exit 1
     exit 1
   fi
 }
 
+update_grant() {
+  read -r -d '' SQL << EOM
+    GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO "$DATABASE_USERNAME";
+    GRANT CONNECT ON DATABASE "$DATABASE_NAME" TO "$DATABASE_USERNAME";
+    GRANT CREATE ON SCHEMA "public" TO "$DATABASE_USERNAME";
+    GRANT USAGE ON SCHEMA "public" TO "$DATABASE_USERNAME";
+    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "$DATABASE_USERNAME";
+    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" TO "$DATABASE_USERNAME";
+EOM
+  psql -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -U "${ROOT_DB_USERNAME}" "${NOT_ASK_FOR_PGPASSWORD}" "${DATABASE_NAME}"  -c "$SQL" -qtAX
+}
+
 printf "Checking of database schema... "
 
-cd "$postgres_folder" || exit_with_error_management $? "Cannot find '$postgres_folder' folder"
+set +e
+
 # check if the database has been initialized
-get_pgsql_value "select count(*) from domain_events" >/dev/null 2>&1
-if [[ $pgsql_value == "" ]]; then
+get_pgsql_value "SELECT COUNT(*) FROM DOMAIN_EVENTS" >/dev/null 2>&1
+if [[ $PGSQL_VALUE == "" ]]; then
   echo "Done. Database is empty!"
   printf "Initializing database... "
-  is_working=true
-  run_script_file $initial_schema >/dev/null 2>&1; exit_with_error_management $? "Cannot run script for initial schema"
-  current_version="0.0.0"
+  IS_WORKING=true
+  run_script_file $INITIAL_SCHEMA_FILE >/dev/null 2>&1
+  exit_with_error_management $? "Cannot run script for initial schema"
+  CURRENT_VERSION="0.0.0"
 else
   # gets the database current version
-  get_pgsql_value "select 'version' from chats_messaging_db_version limit 1" >/dev/null 2>&1
-  if [[ $pgsql_value == "" ]]; then
-    current_version="0.0.0"
+  get_pgsql_value "SELECT VERSION FROM CHATS_MESSAGING_DB_VERSION LIMIT 1" >/dev/null 2>&1
+  if [[ $PGSQL_VALUE == "" ]]; then
+    CURRENT_VERSION="0.0.0"
   else
-    current_version="$pgsql_value"
+    CURRENT_VERSION="$PGSQL_VALUE"
   fi
 fi
-format_version "$current_version"; current_version=$formatted_version
+format_version "$CURRENT_VERSION"; CURRENT_VERSION=$FORMATTED_VERSION
 
 # gets all migration script files from the dedicated folder and puts them in an array sorted by files versions
-cd "$migrations_folder" || exit_with_error_management $? "Cannot find '$migrations_folder' folder"
-migrations_array=()
-for file_name in *; do
-  format_version "$file_name"
-  migrations_array+=("$formatted_version;$file_name")
+cd "$MIGRATIONS_FOLDER" || exit_with_error_management $? "Cannot find '$MIGRATIONS_FOLDER' folder"
+MIGRATIONS_ARRAY=()
+for FILE_NAME in *; do
+  format_version "$FILE_NAME"
+  MIGRATIONS_ARRAY+=("$FORMATTED_VERSION;$FILE_NAME")
 done
-IFS=$'\n' migrations_array=($(sort <<< "${migrations_array[*]}")); unset IFS
+# shellcheck disable=SC2207
+IFS=$'\n' MIGRATIONS_ARRAY=($(sort <<< "${MIGRATIONS_ARRAY[*]}")); unset IFS
 
 # gets all migration script files from the dedicated folder and places them in an array sorted by file versions
-cd "$postgres_folder" || exit_with_error_management $? "Cannot find '$postgres_folder' folder"
-for migrations in "${migrations_array[@]}"; do
-  IFS=';' read -r formatted_version file_name <<< "$migrations"; unset IFS
-  if [[ $formatted_version > $current_version ]]; then
-    if [[ "$is_working" == false ]]; then
+for MIGRATIONS in "${MIGRATIONS_ARRAY[@]}"; do
+  IFS=';' read -r FORMATTED_VERSION FILE_NAME <<< "$MIGRATIONS"; unset IFS
+  if [[ $FORMATTED_VERSION > $CURRENT_VERSION ]]; then
+    if [[ "$IS_WORKING" == false ]]; then
       echo "Done. Database is to be updated!"
       printf "Updating database... "
-      is_working=true
+      IS_WORKING=true
     fi
-    run_script_file "$migrations_folder/$file_name" >/dev/null 2>&1
-    exit_with_error_management $? "Cannot run script file '$migrations_folder/$file_name'"
+    run_script_file "$MIGRATIONS_FOLDER/$FILE_NAME" >/dev/null 2>&1
+    exit_with_error_management $? "Cannot run script file '$MIGRATIONS_FOLDER/$FILE_NAME'"
   fi
 done
 
-if [[ "$is_working" == false ]]; then
+if [[ "$IS_WORKING" == false ]]; then
   echo "Done. The database is already updated."
 else
   echo "Success. The database has been updated."
+  printf "Updating '$DATABASE_USERNAME' grant... "
+  update_grant >/dev/null 2>&1
+  if [[ $? -eq 0 ]]; then
+    echo "Success."
+  else
+    echo "Failed."
+  fi
 fi
-cd "$initial_folder" || exit
+cd "$INITIAL_FOLDER" || exit
